#ifndef LABELS_H___
#define LABELS_H___

/*
 * Alan Ritter 1/13/11
 * Header file for functions included in labels.c
 * For extending Gibbs Sampler generated by HBC to handle LabeledLDA (Ramage et. al. 2009)
 * Also includes some general utility functions for inference based on entities
 */

int **load_labels(char *fname, int *D, int *K);
int *load_entity_map(char *fname, int D);
int sample_Mult_labeled(int w, double **post_beta, double* post_theta, int V, int K, double alpha, double eta, int *labels);
void add_dst(double*dst, double*src, int hi);
int **load_labels_s(char *input, int *D, int *K);

#endif
